### ISSUE TITLE
lain prepare failed if <none> image exists

### ISSUE THREAD

**Issue by ericpai** [laincloud/lain-sdk#7]
Repeat step
1. Find if <none> images exist
```
docker images | grep '<none>'
<none>        <none>    ff32edcc3e17        34 minutes ago      1.808 GB
```
2. Do `lain prepare`
```
>>> Generating prepare image...
Traceback (most recent call last):
  File "/usr/bin/lain", line 9, in <module>
    load_entry_point('lain-cli==2.0.5', 'console_scripts', 'lain')()
  File "build/bdist.linux-x86_64/egg/lain_cli/lain.py", line 68, in main
  File "/usr/lib/python2.7/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "build/bdist.linux-x86_64/egg/lain_cli/prepare.py", line 16, in prepare
  File "build/bdist.linux-x86_64/egg/lain_cli/utils.py", line 57, in lain_yaml
  File "/usr/lib/python2.7/site-packages/lain_sdk-2.0.0-py2.7.egg/lain_sdk/lain_yaml.py", line 35, in __init__
    self.init_act(self.yaml_path, ignore_prepare=ignore_prepare)
  File "/usr/lib/python2.7/site-packages/lain_sdk-2.0.0-py2.7.egg/lain_sdk/lain_yaml.py", line 48, in init_act
    self._prepare_act(ignore_prepare=ignore_prepare)
  File "/usr/lib/python2.7/site-packages/lain_sdk-2.0.0-py2.7.egg/lain_sdk/lain_yaml.py", line 356, in _prepare_act
    shared_prepare_image_name = self.ensure_proper_shared_image()
  File "/usr/lib/python2.7/site-packages/lain_sdk-2.0.0-py2.7.egg/lain_sdk/lain_yaml.py", line 99, in ensure_proper_shared_image
    local_images = self._get_prepare_shared_image_names(False).items()
  File "/usr/lib/python2.7/site-packages/lain_sdk-2.0.0-py2.7.egg/lain_sdk/lain_yaml.py", line 64, in _get_prepare_shared_image_names
    tags = mydocker.get_tag_list_in_docker_daemon(registry, self.appname)
  File "/usr/lib/python2.7/site-packages/lain_sdk-2.0.0-py2.7.egg/lain_sdk/mydocker.py", line 319, in get_tag_list_in_docker_daemon
    for repo_tag in repo_tags:
TypeError: 'NoneType' object is not iterable
```

3. Remove <none> image

```
docker rmi -f ff32edcc3e17
```

4. Do `lain prepare` again

```
>>> Generating prepare image...
>>> found shared prepare image at remote and local, sync ...
>>> Done lain prepare.
```

**Comment by panli889** [comment]
fix at https://github.com/laincloud/lain-sdk/commit/21adfc2c70da16f0e3d527915b07ef038428f89a
